import type { Node, Edge } from '@vue-flow/core'

/** A single code beat for magic-move animation with optional narration metadata */
export interface MagicMoveStep {
  code: string
  title?: string
  comment?: string
  story?: string
  speaker?: string
}

/** Optional metadata for traversal edges between nodes */
export type EdgeTransitionKind =
  | 'default'
  | 'success'
  | 'error'
  | 'warning'
  | 'retry'
  | 'async'

/** Declarative edge metadata for branch labels and styling */
export interface EdgeTransition {
  to: string
  label?: string
  description?: string
  kind?: EdgeTransitionKind
}

/** Props for the FlowTimeline root element */
export interface FlowTimelineProps {
  title: string
  description?: string
  direction?: 'horizontal' | 'vertical'
  minHeight?: number
  layoutEngine?: 'dagre' | 'manual'
  layoutRankSep?: number
  layoutNodeSep?: number
  layoutEdgeSep?: number
}

/** Props for trigger/entry-point nodes */
export interface TriggerNodeProps {
  label: string
  description?: string
  color?: string
  transitions?: EdgeTransition[]
}

/** Props for code block nodes */
export interface CodeNodeProps {
  label: string
  file?: string
  language?: string
  code: string
  comment?: string
  story?: string
  wrapLongLines?: boolean
  magicMoveSteps?: MagicMoveStep[]
  twoslash?: boolean
  transitions?: EdgeTransition[]
}

/** Props for branch/decision nodes */
export interface DecisionNodeProps {
  label: string
  condition?: string
  description?: string
  transitions?: EdgeTransition[]
}

/** Props for payload snapshot/diff nodes */
export interface PayloadNodeProps {
  label: string
  payload?: string
  before?: string
  after?: string
  format?: 'json' | 'yaml' | 'text'
  description?: string
  transitions?: EdgeTransition[]
}

/** Props for failure/error handling nodes */
export interface ErrorNodeProps {
  label: string
  message: string
  code?: string
  cause?: string
  mitigation?: string
  transitions?: EdgeTransition[]
}

/** Props for prose/description nodes */
export interface DescriptionNodeProps {
  label: string
  body: string
  transitions?: EdgeTransition[]
}

/** Props for link/reference nodes */
export interface LinkNodeProps {
  label: string
  href: string
  description?: string
  transitions?: EdgeTransition[]
}

/** Union of all node prop types */
export type AnyNodeProps =
  | TriggerNodeProps
  | CodeNodeProps
  | DecisionNodeProps
  | PayloadNodeProps
  | ErrorNodeProps
  | DescriptionNodeProps
  | LinkNodeProps

/** VueFlow custom node type names */
export type FlowNodeType =
  | 'trigger'
  | 'code'
  | 'decision'
  | 'payload'
  | 'error'
  | 'description'
  | 'link'

/** Data payload attached to each VueFlow node */
export interface FlowNodeData {
  key: string
  type: FlowNodeType
  elementType: string
  props: Record<string, unknown>
  index: number
}

export type FlowNode = Node<FlowNodeData>
export type FlowEdge = Edge

/** A single element in the flat spec */
export interface SpecElement {
  type: string
  props: Record<string, unknown>
  children?: string[]
}

/** The json-render spec format for flow-narrator */
export interface FlowNarratorSpec {
  root: string
  elements: Record<string, SpecElement>
  state?: Record<string, unknown>
}

/** A single flow entry in a multi-flow manifest */
export interface FlowNarratorManifestFlow {
  id: string
  title?: string
  description?: string
  src: FlowNarratorSpec | string
  tags?: string[]
  entrypoints?: string[]
}

/** Multi-flow manifest generated by AI harnesses */
export interface FlowNarratorManifest {
  version?: number
  defaultFlowId?: string
  flows: FlowNarratorManifestFlow[]
}

/** Runtime-friendly flow option metadata */
export interface FlowNarratorFlowOption {
  id: string
  title: string
  description?: string
  tags?: string[]
  entrypoints?: string[]
}

/** Spec object, manifest object, or remote/local JSON source */
export type FlowNarratorSource = FlowNarratorSpec | FlowNarratorManifest | string

/** Public component props */
export interface FlowNarratorProps {
  src: FlowNarratorSource
  autoPlay?: boolean
  interval?: number
}
